### ISSUE TITLE
feature_request) table의 행 개수를 새는 get_row_num 추가

### ISSUE THREAD

**Issue by jp1924** [martiniifun/pyhwpx#2]
안녕하세요?
pyhwpx라는 멋진 패키지를 만들어 주셔서 감사합니다.

기능 중에 table의 열의 개수를 새는 `get_col_num`는 있지만

행의 개수를 새어주는 `get_row_num`는 없습니다.

그래서 관련 기능 요청을 제안 드립니다. 

혹은 이 기능을 pyhwpx에서 제공하는 기능들과 엮어서 구현할 수 있는 방법이 있을까요?

**Comment by martiniifun** [comment]
jp님 반갑습니다.
최신업데이트(0.15.1)에
get_row_num을 추가해 두었습니다.
열마다 순회하면서 최대 행번호를 리턴하는 메서드입니다.
(일부 열에 행병합이 있는 경우가 있기 때문입니다.)

다만, 극단적으로 아래와 같은 경우에는 
실제 최대 행 갯수는 6이지만 get_row_num은 7을 리턴합니다.
![녹화_2024_06_23_08_21_44_273](https://github.com/martiniifun/pyhwpx/assets/62679294/4bb9f71d-2a13-4107-975f-49180b1635f3)

보완이 필요하거나 오류가 발생하는 경우
간단히 알려주시면 조치하도록 하겠습니다.

감사합니다! 행복한 하루 되세요^^

**Comment by jp1924** [comment]
빠르게 기능을 추가해 주셔서 정말 감사합니다!
