### ISSUE TITLE
ctrl 객체 활용 문의

### ISSUE THREAD

**Issue by jp1924** [martiniifun/pyhwpx#3]
안녕하세요? pyhwpx라는 멋진 라이브러리를 만들어 주셔서 감사합니다.

`hwp.get_into_nth_table` 메소드는 선택한 테이블의 ctrl 객체로 부터 html이나 그 외의 text를 추출하는 방법이 있을까요?

이전에는 아래 코드와 같이 새로운 hwp 창에다 table 등의 객체를붙여넣은 뒤 
get_text_file 메소드를 이용해 html을 얻어 왔습니다.
```python
from pyhwpx import Hwp
hwp = Hwp()
hwp.add_doc()
hwp.switch_to(0)

hwp_path = ""
hwp.open(hwp_path)

ctrl = hwp.get_into_nth_table(0)
hwp.select_ctrl(ctrl)
hwp.Copy()
hwp.switch_to(1)
hwp.Paste()

html_txt = hwp.get_text_file(format="HTML") # to save

ctrl = hwp.get_into_nth_table(0)
hwp.DeleteCtrl(ctrl)
hwp.switch_to(0)
```

하지만 이런 방식은 여러모로 많은 문제점이 있습니다. 
복사를 할 때 여러 확인창, 경고창 등이 떠서 코드가 수행되지 않는 경우가 많습니다.

그래서 ctrl에서 객체의 값을 추출하는 방법이 있을지 궁금합니다.

감사합니다.

**Comment by martiniifun** [comment]
안녕하세요?
get_text_file은 선택한 블록만 저장할 수 있는 옵션이 있습니다.
복사-붙여넣기 과정 없이 아래처럼 실행해보세요.

```
from pyhwpx import Hwp
hwp = Hwp()
hwp_path = ""
hwp.open(hwp_path)

html_list = []
for i in range(3):
    hwp.get_into_nth_table(0)
    hwp.select_ctrl(hwp.ParentCtrl)
    html_list.append(hwp.get_text_file("HTML", option="saveblock"))
    hwp.DeleteCtrl(hwp.CurSelectedCtrl)
```

![녹화_2024_08_06_11_46_14_433](https://github.com/user-attachments/assets/61db4e7f-409b-4ca4-8aac-38900bcf179c)

핵심은 `option="saveblock"`입니다.
