### ISSUE TITLE
hwp.Copy() 시 win32clipboard의 clipboard에 복사되게 만드는 방법에 대한 문의

### ISSUE THREAD

**Issue by jp1924** [martiniifun/pyhwpx#4]
hwp.Copy()를 할때 win32clipboard의 clipboard로 복사되게 만들 수 있나요?

아래와 예시와 같이 `OpenClipboard`가 되어 있는 상황에서 
hwp.Copy()으로 win32clipboard에 만드는 방법이 pyhwpx 가능할까요?
```python
import win32clipboard as clipboard
from pyhwpx import Hwp

clipboard.OpenClipboard()

hwp = Hwp()

file_path = ""
hwp.open(file_path)

ctrl = hwp.HeadCtrl
while ctrl:
    if ctrl.UserDesc != "표":
        ctrl = ctrl.Next
        continue
    hwp.select_ctrl(ctrl)
    hwp.Copy()  # 복사와 동시에 win32clipboard의 clipboard에 저장됨.

    ctrl = ctrl.Next
clipboard.CloseClipboard()
```

**Comment by martiniifun** [comment]
안녕하세요?
hwp의 Copy 메서드와 win32clipboard는 
이미 같은 클립보드 공간을 공유하고 있습니다.
텍스트는 쉽게 꺼내올 수 있는 반면,
텍스트와 메타데이터를 포함한 클립보드 데이터는
(예를 들면 아래아한글 문서의그림이나 표, 또는 서식을 포함한 문서 특정 영역)
접근하거나 수정할 때 조금 번거로운 과정을 거쳐야 하는데요.

win32clipboard로 제어하는 클립보드 안에서도 
"HWP NATIVE"가 등록해서 사용중인 클립보드 공간을 찾아서
데이터를 꺼내와야 합니다.

> 아래아한글에만 해당하는 이야기는 아니고,
> 클립보드를 특수하게 사용하고 있는 오피스 제품군이나 
> 어도비 제품군 등 대부분의 윈도우 애플리케이션들이 
> 고유의 클립보드 영역을 가지고 있습니다.

그리고 이 과정이 번거로운 가장 큰 이유는
HWP NATIVE가 차지하는 클립보드 영역의 고유번호가 매번 바뀌기 때문에,
매번 클립보드 모든 공간을 탐색해야 한다는 점인데요..


그래서 개인적인 생각은,
가급적 win32clipboard를 사용하지 않으시는 걸 추천드립니다^^;

혹시 어떤 문제 때문에 그러시는지요?
전체 과업을 알면 다른 방식으로 도움 드릴 수 있을 것 같습니다.

**Comment by jp1924** [comment]
현재 제가 수행하고 있는 작업은 AI에 학습에 사용될 table 이미지를 얻기 위해, 
hwp파일에서 온전한 html table(css도 포함된)을 추출하는 코드를 제작하고 있습니다.

굳이 CSS가 포함되어야 하는 이유는 단순 html코드만 추출하면 이미지나 너무 단순해져, 
학습 데이터로 사용할 수가 없어서 입니다. 정리하면, 조건으로
1. 무조건 html코드여야 함.
2. html에 css 정보가 포함되어, 웹에서 표현된 table과 hwp상의 table이 똑같이 표현되어야 함.

입니다.

방법을 찾다가, Copy를 수행후 clipboard에는 html + css가 포함된 코드가 byte형태로 저장되는 것을 발견 했습니다.
그래서 매 table마다 hwp.Copy()로 복사해 1차로 clipboard에 권한 얻음,  2차로 clipboard에서 html+css코드를 추출, 
3차로 clipboard권한 반환을 하는 형태로 기능을 제작 했습니다.

하지만 이 방법은 다음과 같은 문제가 있습니다.

1. 속도가 너무 느림
2. win32clipboard의 권한 문제가 빈번하게 발생함.
4. win32clipboard가 복사, 붙여넣기 권한을 가져감.

현재 3번 문제 때문에 win32clipboard가 권한을 가져간뒤의 hwp.Copy()가 수행되질 않아, 
매번 clipboard의 권한을 줬다, 놨다를 반복하고 있습니다. 이런 문제로 1번, 2번 문제가 동시에 발생합니다.

그렇기에 clipboard의 권한을 한번만 가져온 뒤 hwp.Copy() 시의 결과물을 win32clipboard에 
저장하는 방법이 궁금해 이슈를 남기게 되었습니다.

아니면 이 외에 html+css코드를 추출하는 다른 방법이 있을까요?

---
PS

예전에는 https://github.com/martiniifun/pyhwpx/issues/1 와 같이 별도 hwp문서에 table객체를 복사한 뒤 html+css코드를 저장하는 형태로 작성했습니다.
그러나 여러 문제로 인해, 매우 느린데다 불안정한 문제가 있었습니다.

현재 코드에선 하나의 hwp파일 상에 여러 파일을 hwp.open()으로 파일을 바꿔가며 작업하도록 수정하였기에, 
안정성은 확보가 되었으나, 상술한 문제 때문에 시간이 너무 오래걸리는 문제가 있습니다.

감사합니다.

**Comment by martiniifun** [comment]
다 아시는 내용이거나, 이미 적용되어 있을 수 있지만,
① 추출속도는 Visible 속성이 False일 때(백그라운드로 숨겨져 있을 때) 수십배 빨라지는 경우가 있습니다.
② 가급적 클립보드를 쓰지 마시고, `hwp.GetTextFile("HTML", option="saveblock")`로 실행하시는 걸 추천드립니다.
    속도에 유의미한 차이가 있는지는 모르겠지만, hwp.Copy() 메서드 자체는 (스레딩 때문?) 씹히는 오류가 있습니다.
    반복작업을 해보시면 아시겠지만, 짧고 빠른 연산이 반복되는 경우 두드러지게 오류가 나타납니다.
(참고 : https://blog.naver.com/pythonrpa/223509736759)

③ 그리고 말씀하시는 클립보드 권한 관련 오류는 win32clipboard를 열고닫고 비우는 순서에 문제가 있는 것 같기도 한데,
    pyperclip 모듈의 copy(), paste() 메서드를 사용해보시는 걸 추천드립니다. 단, 바이트는 무시하고 텍스트만 복사되므로
    GetTextFile과 연계하여 사용하시면 됩니다.

제가 jp님 문제를 잘 못 짚은 것 같기도 하고요^^;
코멘트 부탁드립니다.

**Comment by jp1924** [comment]
@martiniifun님 답변과 조언 감사합니다.

제 설명이 부족 했습니다.

![문서 table](https://github.com/user-attachments/assets/a0fa3470-5cb1-4329-a77a-328798773edd)
원본 문서에서 사진과 같이 표현되는 테이블이라도

`hwp.GetTextFile("HTML", option="saveblock")`로 추출한 방식은,

![get_text_file](https://github.com/user-attachments/assets/29b2749d-0cbc-4af7-8ad0-108074f7e5a4)

같이 깨져서 표현되지만, win32clipboard에서 추출한 방식은

![get_html_table_from_clipboard](https://github.com/user-attachments/assets/0e27fad5-f786-4057-805e-ce4ae7d6e773)

같이 온전한 형태를 담은 상태로 표현 되기에 GetTextFile의 대안으로 win32clipboard를 사용하게 되었습니다.

win32clipboard와 GetTextFile의 차이는 다음과 같습니다.

clipboard를 이용하는 방식은 [예시](https://github.com/jp1924/HF_builders/blob/main/src/correct_html_extract.html#L423C5-L423C11)와  같이 `hwp_editor_board_content` 테그를 이용해 table이 표현되지만,

GetTextFile는 [예시](https://github.com/jp1924/HF_builders/blob/main/src/wrong_html_extract.html#L355-L592)와 같이 `hwp_editor_board_content`에 표현되어 있는 객체가 전부 풀어 해쳐져 표현이 됩니다.

현재 clipboard에 접속해 html을 추출하는 이 방식은 너무나 기형적입니다.

그렇기에 hwp의 api상에서 win32clipboard를 사용한 것과 동일하게 
`hwp_editor_board_content`가 포함된 상태의 html을 추출하는 기능을 있을거라 생각 했습니다.

그래서 이러한 기능이 pyhwpx에 구현되어 있는지 궁금해 이슈를 남기게 되었습니다.

감사합니다.

**Comment by martiniifun** [comment]
제가 질문의 요지를 잘 파악하지 못했던 것 같네요.

클립보드는 항상 하나의 어플리케이션만 접근할 수 있게 락이 걸립니다.
win32clipboard.OpenClipboard()가 실행된 상태에서는
다른 모든 어플리케이션(프로세스)의 Copy 및 Paste 관련 기능이 잠깁니다.
일종의 뮤텍스처럼요.

그래서 win32clipboard는 필히 매번 열고 닫고를 반복해야 합니다.

그리고 제 주관적인 생각이기는 한데, 
win32clipboard를 열고 닫는 속도가, 프로세스에 지장이 있을 정도로 느리지는 않은 듯 해요.
제 저사양 태블릿에서 용량이 제법 큰 클립보드 내용을 조회하고 닫아도 0.001초 남짓 걸리거든요.

속도 개선의 여지가 있는 부분은 아마 hwp를 조작하는 파트가 아닌가 싶기도 합니다.
(특히 pyhwpx는 죄송한 말씀이지만 최적화가 개똥 같거든요ㅜㅜㅜㅜㅜㅜㅜㅜ)

아래 코드를 한 번 참고해주시기 바랍니다. (hwp 오토메이션 API가 pyhwpx보다는 훨씬 빠릅니다.)

```
import win32clipboard
import win32com.client as win32

hwp = win32.gencache.EnsureDispatch("hwpframe.hwpobject")
hwp.RegisterModule("FilePathCheckDLL", "FilePathCheckerModule")
hwp.XHwpWindows.Item(0).Visible = False

file_path = r"C:\Users\Administrator\Desktop\simple_table.hwp"
hwp.Open(file_path)

html_list = []

ctrl = hwp.HeadCtrl
while ctrl:
    if ctrl.UserDesc == "표":
        hwp.SetPosBySet(ctrl.GetAnchorPos(0))
        hwp.HAction.Run("SelectCtrlFront")
        hwp.HAction.Run("Copy")
        win32clipboard.OpenClipboard()
        html_list.append(
            win32clipboard.GetClipboardData(49515).decode("UTF-8").split("\r\n", maxsplit=6)[-1]
        )
        win32clipboard.CloseClipboard()
    ctrl = ctrl.Next
hwp.Quit()

print(html_list)
```

**Comment by jp1924** [comment]
@martiniifun님이 작성하신 코드가 제 코드보다 속도가 더 빠르네요,
아마 `RegisterClipboardFormat` 덕분에 안정성이 높아져, thread 문제가 덜 발생해 속도가 개선된 것 같습니다.

제공해 주신 코드 덕분에 많은 도움이 되었습니다, 정말 감사합니다!
